import logo from "./logo.png"
import about from "./about.jpg"
import altFeatures from "./alt-features.png"
import heroImg from "./hero-img.png"
import favicon from "./favicon.png"
import appleTouchICon from "./apple-touch-icon.png"
import features from "./features.png"
import heroBG from "./hero-bg.png"
import Services from "./services.jpg"
import Values1 from "./values-1.png"
import Values2 from "./values-2.png"
import Values3 from "./values-3.png"
import LogoUK from "./logoUnklab.png"

export{logo, about, altFeatures, heroImg, favicon, appleTouchICon, features, heroBG, Services, Values1, Values2, Values3, LogoUK};