import Blog1 from "./blog-1.jpg"
import Blog2 from "./blog-2.jpg"
import Blog3 from "./blog-3.jpg"
import Blog4 from "./blog-4.jpg"
import BlogAuthor from "./blog-author.jpg"
import BlogInsidePost from "./blog-inside-post.jpg"
import BlogRecent1 from "./blog-recent-1.jpg"
import BlogRecent2 from "./blog-recent-2.jpg"
import BlogRecent3 from "./blog-recent-3.jpg"
import BlogRecent4 from "./blog-recent-4.jpg"
import BlogRecent5 from "./blog-recent-5.jpg"
import Comments1 from "./comments-1.jpg"
import Comments2 from "./comments-2.jpg"
import Comments3 from "./comments-3.jpg"
import Comments4 from "./comments-4.jpg"
import Comments5 from "./comments-5.jpg"
import Comments6 from "./comments-6.jpg"

export{Blog1, Blog2, Blog3, Blog4, BlogAuthor, BlogInsidePost, BlogRecent1, BlogRecent2, BlogRecent3, BlogRecent4, BlogRecent5, Comments1, Comments2, Comments3, Comments4, Comments5, Comments6};